title = "Kestrel Packages"
gitRepoUrl = "https://github.com/Kestrel-UGC-Solutions/kestrel-packages"
gitSourceBranch = "main"

[[classOrder]]
section = "Admin Abuse"
classes = ["AdminAbuse", "State", "EventMultipliers", "Signals", "Ping", "Polling", "Boot", "Cache"]

[home]
enabled = true
includeReadme = false


[[navbar.items]]
href = "https://github.com/Kestrel-UGC-Solutions/wally-index"
label = "Wally Index"
position = "right"

[docusaurus]
tagline = " "
organizationName = "Kestrel-UGC-Solutions"
projectName = "kestrel-packages"
url = "https://Kestrel-UGC-Solutions.github.io"
baseUrl = "/kestrel-packages/"
[footer]
style = "dark"
copyright = "Copyright © 2024-2026 Kestrel UGC Solutions. Built with Moonwave and Docusaurus."
