[package]
name = "kestrel/admin-abuse"
description = "Admin abuse event system for Roblox."
version = "0.1.0"
license = "MIT"
registry = "https://github.com/Kestrel-UGC-Solutions/wally-index"
realm = "server"
include = ["src", "src/**", "wally.toml", "default.project.json"]

[dependencies]
Signal = "sleitnick/signal@2.0.3"
Trove = "sleitnick/trove@1.8.0"
